config/routes.rb
Rails.application.routes.draw do
  resources :events, only: %i[show new create] do
    get 'result'
    resources :votes, only: %i[new create]
    resources :scores, only: %i[create destroy]
  end
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evaluation_item.rb
class EvaluationItem < ApplicationRecord
  belongs_to :event

  has_many :scores, dependent: :destroy
  has_many :votes, dependent: :destroy

  scope :default_order, -> { order(id: :desc) }
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :evaluation_items, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :name, presence: true
  validates :password, presence: true
  validates :point, presence: true, numericality: { only_integer: true }

  scope :default_order, -> { order(id: :desc) }
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :team
  belongs_to :evaluation_item
  belongs_to :vote
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :event

  has_many :scores, dependent: :destroy
  has_many :votes, dependent: :destroy

  scope :default_order, -> { order(id: :desc) }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :event

  has_many :scores, dependent: :destroy

  accepts_nested_attributes_for :scores

  validate :validate_points_within_limit

  scope :default_order, -> { order(id: :desc) }

  private

  def validate_points_within_limit
    total_points = scores.sum(&:point)
    if total_points > event.point
      errors.add(:base, "持ち点以上の点数を投票することはできません。")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show]

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.teams = params[:event][:teams].split(' ').map { |name| Team.new(name:) }
    @event.evaluation_items = params[:event][:evaluation_items].split(' ').map { |name| EvaluationItem.new(name:) }

    if @event.save
      redirect_to event_path(@event), notice: t('controllers.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def result
    @event = Event.find(params[:event_id])
    if @event.password == params[:password]
      render :result
    else
      redirect_to event_path(@event), notice: "パスワードが正しくありません。再度入力してください。"
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :password, :point)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_event, only: %i[create destroy]

  def create
    @evaluation_item = @event.evaluation_items.find(params[:evaluation_item_id])
    @team = @event.teams.find(params[:team_id])
    @score = @team.scores.build(evaluation_item: @evaluation_item, team: @team)
    @score.save!
  end

  def destroy
    @evaluation_item = @event.evaluation_items.find(params[:evaluation_item_id])
    @team = @event.teams.find(params[:team_id])
    @score = @team.scores.find_by!(evaluation_item: @evaluation_item, team: @team)
    @score.destroy!
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_event, only: %i[new create edit update]

  def new
    @vote = @event.votes.build
  end

  def create
    @vote = @event.votes.build(vote_params)
    if @vote.save
      redirect_to root_path, notice: t('controllers.created')
    else
      render :new
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def vote_params
    params.require(:vote).permit(scores_attributes: [:team_id, :evaluation_item_id, :point])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_qr_code(url, size: 200)
    qrcode = RQRCode::QRCode.new(url)
    png = qrcode.as_png(size: size)
    Base64.encode64(png.to_s)
  end
end

app/views/events/new.html.haml
- if @event.errors.present?
  %ul
    - @event.errors.full_messages.each do |message|
      %li= message

.w-full.max-w-xs{date_controller: 'events'}
  = form_with model: @event, url: events_path, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4', id: 'event-form' do |f|
    .mb-4
      = f.label :name, "イベント名", class: 'block text-gray-700 text-sm font-bold mb-2'
      = f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

    .mb-4
      = f.label :password, "パスワード", class: 'block text-gray-700 text-sm font-bold mb-2'
      = f.password_field :password, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

    .mb-4
      = f.label :point, "持ち点", class: 'block text-gray-700 text-sm font-bold mb-2'
      = f.number_field :point, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

    .mb-4
      %label.block.text-gray-700.text-sm.font-bold.mb-2{ for: 'teams' } チーム名
      .taggle#teams-input
      = f.hidden_field :teams

    .mb-4
      %label.block.text-gray-700.text-sm.font-bold.mb-2{ for: 'evaluation_items' } 評価項目
      .taggle#evaluation-items-input
      = f.hidden_field :evaluation_items

    = f.submit "イベントを作成", class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none cursor-pointer dark:focus:ring-blue-800'

app/views/events/result.html.haml
%h1 結果画面

%p
  回答人数
  = @event.votes.count

- @event.teams.each do |team|
  .mb-6
    %p.text-3xl= team.name
    %p
      合計得点:
      = team.scores.sum(:point)
    %ul
      - @event.evaluation_items.each do |evaluation_item|
        %li= evaluation_item.name
        %li= evaluation_item.scores.where(team:).sum(:point)

app/views/events/show.html.haml
%p.text-3xl= @event.name
%p
  回答人数
  = @event.votes.count

= image_tag "data:image/png;base64,#{generate_qr_code(new_event_vote_url(@event))}"
= link_to new_event_vote_url(@event), new_event_vote_url(@event)

%button.block.text-white.bg-blue-700.hover:bg-blue-800.focus:ring-4.focus:outline-none.focus:ring-blue-300.font-medium.rounded-lg.text-sm.px-5.text-center.dark:bg-blue-600.dark:hover:bg-blue-700.dark:focus:ring-blue-800{:class => "py-2.5", "data-modal-target" => "defaultModal", "data-modal-toggle" => "defaultModal", :type => "button"}
  投票結果を見る
#defaultModal.fixed.top-0.left-0.right-0.z-50.hidden.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.max-h-full{"aria-hidden" => "true", :class => "h-[calc(100%-1rem)]", :tabindex => "-1"}
  .relative.w-full.max-w-2xl.max-h-full
    .relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
      .flex.items-start.justify-between.p-4.border-b.rounded-t.dark:border-gray-600
        %h3.text-xl.font-semibold.text-gray-900.dark:text-white
          パスワードを入力してください
        %button.text-gray-400.bg-transparent.hover:bg-gray-200.hover:text-gray-900.rounded-lg.text-sm.ml-auto.inline-flex.items-center.dark:hover:bg-gray-600.dark:hover:text-white{:class => "p-1.5", "data-modal-hide" => "defaultModal", :type => "button"}
          %svg.w-5.h-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
            %path{"clip-rule" => "evenodd", :d => "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
          %span.sr-only Close modal
      .p-6.space-y-6
        = form_with url: event_result_path(@event), method: :get do |f|
          = f.text_field :password
          .flex.items-center.p-6.space-x-2.border-t.border-gray-200.rounded-b.dark:border-gray-600
            = f.submit '結果画面', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800', "data-modal-hide" => "defaultModal"

app/views/homes/index.html.haml
= link_to 'イベントを作成', new_event_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'

app/views/layouts/_inspector.html.haml
- if Rails.env.development?
  :plain
    <script type="module" src="https://cdn.skypack.dev/@aki77/rails-template-inspector@^0.5.0"></script>
    <rails-inspector url-prefix="x-mine://open?file=" root="#{Rails.root}" combo-key="command-shift-v"></rails-inspector>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VoteApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
  %body.container.mx-auto.p-4.max-w-2xl
    = yield
    = render 'layouts/inspector'

app/views/votes/new.html.haml
.w-full
  - if @event.errors.present?
    %ul
      - @vote.errors.full_messages.each do |message|
        %li= message
  = form_with model: @vote, url: event_votes_path(@event), class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f|
    - @event.teams.each do |team|
      .mb-6
        %p.text-3xl= team.name
        - @event.evaluation_items.each do |evaluation_item|
          %p= evaluation_item.name
          = f.fields_for :scores, @vote.scores.build  do |score|
            = score.hidden_field :team_id, value: team.id
            = score.hidden_field :evaluation_item_id, value: evaluation_item.id
            = score.number_field :point, min: 0

    = f.submit "投票", class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none cursor-pointer dark:focus:ring-blue-800'